### ISSUE TITLE
[feat] 규칙홈/ 오늘의 to-do 리사이클러뷰 기능 구현

### ISSUE THREAD

**Issue by murjune** [TeamHous/Hous-Android#43]
## 화면 이름
![image](https://user-images.githubusercontent.com/87055456/178988545-22eb888a-29be-4058-9551-da485344c80b.jpeg)

## 작업 내용 설명
- 오늘의 to-do 리사이클러뷰 기능 구현

## 필요 태스크
- [x] 오늘의 to-do Data class 만들기(서버 명세서보고)
- [x] 오늘의 to-do Adapter 구현
- [x] 오늘의 to-do ViewModel 구현
- [x] 오늘의 to-do Model - View - ViewModel 연결~. 
- [x] 오늘의 to-do 담당자 text 기능 구현. 
- [x] 오늘의 to-do 담당자 명 수마다 동그라미 형태 바꾸기. 
- [x] 오늘의 to-do 담당자 성향에 따라 동그라미 색 넣기

## 시작일/ 마감일
07-13 ~ 07-14
